
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcqqvddhfxvfiugysxga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcXF2ZGRoZnh2Zml1Z3lzeGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDY2NzYsImV4cCI6MjA1NzQ4MjY3Nn0.KM036c0MSsKaWW3K2mgB9uxREKxPQh8VTbn46jx_GwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// أنواع مهمة للتطبيق
export type Profile = {
  id: string;
  name: string | null;
  avatar_url: string | null;
  role: string;
  created_at: string;
  updated_at: string;
};

export type AdminUser = {
  name: string;
  email: string;
  role: 'super' | 'helper';
};
